### ISSUE TITLE
Composer can't find package

### ISSUE THREAD

**Issue by rapidtechsolutions** [jedlikowski/laravel-nextcloud#1]
composer require jedlikowski/laravel-nextcloud

  [InvalidArgumentException]
  Could not find a matching version of package jedlikowski/laravel-nextcloud. Check the package spelling, your version constraint and that the pa
  ckage is available in a stability which matches your minimum-stability (dev).

**Comment by rapidtechsolutions** [comment]
Submitted package to packagist.

**Comment by jedlikowski** [comment]
Hey @rapidtechsolutions I only see your issue now, looks like github hasn't sent me any email about it 😱 . 
Anyway, can you remove the package from packagist? I can submit it myself right after you do that, but right now you are blocking my namespace `jedlikowski` and I can't submit any packages. Unless of course I change the namespace and I would rather not because it's my last name 😄

**Comment by rapidtechsolutions** [comment]
@jedlikowski done! :)

**Comment by jedlikowski** [comment]
@rapidtechsolutions package submitted to Packagist again, should be ok now although I haven't tested it. Thank you
